# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# Alterar trigger conforme necessario

# É mais facil configurar para reiniciar um app service se colocar um build-id
# Pode colocar com latest mas dessa forma, a imagem será subscrita e além de não ter a versão anterior mais,  

# Coloque o assinatura conforme necessario
# Coloque o nome da imagem
# Coloque o tipo de registro (caso seja DockerHub ou Azure Registry)

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repository-image: '' # image-template
  registry: 'vihuro.azurecr.io'
  subscription: 'Personal signature(1)(8cea3c6a-393b-4160-9350-46ef45ae09b1)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: 'Azure Registry'
        repository: '$(repository-image)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: './'
        tags: '$(tag)'

    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to App Service
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(subscription)'
        appType: 'webAppContainer'
        WebAppName: ''
        DockerNamespace: '$(registry)'
        DockerRepository: '$(repository-image)'
        DockerImageTag: '$(tag)'